### ISSUE TITLE
FastAPI部分のDocker起動修正

### ISSUE THREAD

**Issue by shuhei-fujita** [shuhei-fujita/playground-mysql#18]
- [ ] Python仮想環境の構築（poetry or python -m）
- [ ] Python仮想環境の、Dockerでの使用方法
- [ ] docker-compose.yamlとDockerfileの併用方法（apiとdbでリポジトリを切り話す可能性があるため）

Endpoint
- API: http://localhost:8080/
- DB: http://127.0.0.1:8000/docs

https://chat.openai.com/c/b1d72952-c40f-4e16-a2a9-cefe6112ce0c
https://fastapi.tiangolo.com/ja/deployment/docker/

**Comment by shuhei-fujita** [comment]
```bash
~/git/sample/playground-mysql  ‹feature/fix-bug-about-launch-docker*› $ docker run -it --entrypoint /bin/bash playground-mysql-api                                        
root@ee895bc40eb8:/app# ls
Dockerfile  README.md  __pycache__  logs  main.py  requirements.txt  src
root@ee895bc40eb8:/app# pwd
/app
root@38a505a96d76:/app# ls -la
total 56
drwxr-xr-x 1 root root 4096 Nov  4 16:39 .
drwxr-xr-x 1 root root 4096 Nov  5 16:35 ..
-rw-r--r-- 1 root root   12 Oct 26 11:04 .gitignore
drwxr-xr-x 1 root root 4096 Nov  5 16:35 .venv
-rw-r--r-- 1 root root  501 Oct 26 11:04 Dockerfile
-rw-r--r-- 1 root root 1325 Nov  4 15:43 README.md
drwxr-xr-x 2 root root 4096 Nov  4 16:39 __pycache__
drwxr-xr-x 1 root root 4096 Nov  4 15:55 logs
-rw-r--r-- 1 root root 2119 Nov  4 16:08 main.py
-rw-r--r-- 1 root root   74 Nov  4 16:13 requirements.txt
drwxr-xr-x 4 root root 4096 Nov  4 16:39 src
root@38a505a96d76:/app# ls -la .venv/bin
total 56
drwxr-xr-x 2 root root 4096 Nov  4 14:43 .
drwxr-xr-x 1 root root 4096 Nov  5 16:35 ..
-rw-r--r-- 1 root root 9033 Nov  4 14:43 Activate.ps1
-rw-r--r-- 1 root root 2020 Nov  4 14:43 activate
-rw-r--r-- 1 root root  946 Nov  4 14:43 activate.csh
-rw-r--r-- 1 root root 2088 Nov  4 14:43 activate.fish
-rwxr-xr-x 1 root root  259 Nov  4 14:43 dotenv
-rwxr-xr-x 1 root root  268 Nov  4 14:43 pip
-rwxr-xr-x 1 root root  268 Nov  4 14:43 pip3
-rwxr-xr-x 1 root root  268 Nov  4 14:43 pip3.10
lrwxrwxrwx 1 root root    7 Nov  4 14:43 python -> python3
lrwxrwxrwx 1 root root   54 Nov  4 14:43 python3 -> /Users/shuhei/.asdf/installs/python/3.10.5/bin/python3
lrwxrwxrwx 1 root root    7 Nov  4 14:43 python3.10 -> python3
-rwxr-xr-x 1 root root  258 Nov  4 14:43 uvicorn
root@38a505a96d76:/app# source .venv/bin/activate
(.venv) root@38a505a96d76:/app#
(.venv) root@38a505a96d76:/app# uvicorn main:app --host 0.0.0.0 --port 8000
mysql://None:None@localhost:None/None
INFO:     Started server process [76]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/app/main.py", line 64, in startup_event
    await connect_to_db()
  File "/app/src/database.py", line 19, in connect_to_db
    await database.connect()
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 112, in connect
    await self._backend.connect()
  File "/usr/local/lib/python3.10/site-packages/databases/backends/mysql.py", line 71, in connect
    port=self._database_url.port or 3306,
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 546, in port
    return self.components.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'None'

ERROR:    Application startup failed. Exiting.
(.venv) root@38a505a96d76:/app# python3 --version
Python 3.10.5
```
